### ISSUE TITLE
stop storing binaries in version control

### ISSUE THREAD

**Issue by cup** [mono/roslyn-binaries#9]
i see the executable files are stored in version control here

https://github.com/mono/roslyn-binaries/tree/master/Microsoft.Net.Compilers/3.1.0

there really is no point of putting these in version control, as you can just
create releases with attached binaries here

https://github.com/mono/roslyn-binaries/releases

**Comment by akoeplinger** [comment]
It is more convenient as we can switch between different versions more easily.

In general storing binaries in a git repository is a bad idea but until we can consume the roslyn from the nuget packages we'll use this repo here.
